### ISSUE TITLE
Google News in verschiedenen Sprachen

### ISSUE THREAD

**Issue by caeschfloh** [trovu/trovu.github.io#5]
Hi Georg,

The latest Updates have killed Google News?
How should I search for English, French, and Spanish articles now?
neither es.gns, nor .fr.gns nor en.gn works.

I've seen you also changed leo but haven't found the new logic for Google News.

**Comment by georgjaehnig** [comment]
Thanks for the issue, I can verify problems around `gns` but not `gn`.

So basically, `gn` is country-related, pointing to news.google.com. `gns` is language-related, pointing to google.com's news tab.

Both take either your `language` or `country` settings, or you can override them with e.g. `.es` (Spain) or `es` (Spanish). So `.es.gn berlin` searches Google News from Spain about *berlin*. Make sure there exists a Google News for this country.

Now, for Spanish news, no matter from which country, use `gns` (respectively `es.gns`). I can verify it doesn't work now – but the problem seems at Google – I'm unable to get a URL to news in Spanish. Do you?

**Comment by caeschfloh** [comment]
Ok, fine. 
This one works for Spanish, too. It includes US, Spanish and Latin American sources:
https://news.google.com/search?q={%search}&hl=es-419&gl=US&ceid=US%3Aes-419

It slightly differs from (es.gns) https://www.google.de/search?q={%search}&tbm=nws&hl=es

Beyond es.gn, after a reload, GN works fine now again, here. Thank you.

**Comment by georgjaehnig** [comment]
> https://news.google.com/search?q={%search}&hl=es-419&gl=US&ceid=US%3Aes-419

OK, that's a URL for news.google.com, `gn` in Trovu – that one seems to work fine. It shows the news per-country.

Now, `gns` or https://www.google.de/search?q=berlin&tbm=nws&hl=es should deliver news on a per-language basis. Do you manage to get a working URL for e.g. news about Berlin in Spanish. Because I don't, also not for other languages – seems, as something has changed.

**Comment by caeschfloh** [comment]
yes, gns works fine for my languages (es,en,fr) now. Maybe you need a reload, or something in your personal shortcut file is overriding?

fr.gns Berlin → https://www.google.de/search?q=Berlin&tbm=nws&hl=fr → All French

**Comment by georgjaehnig** [comment]
> fr.gns Berlin → https://www.google.de/search?q=Berlin&tbm=nws&hl=fr → All French

Hm, that's weird. When I click this link, I see this:

![image](https://user-images.githubusercontent.com/1092628/231882016-e8c9bf85-4dbd-4256-85b7-92db4c76fdea.png)

The interface is French – but the articles are German. A friend confirms on his machine the same.

And you see French articles, yes?

**Comment by caeschfloh** [comment]
oui, monsieur, tout en francais.

It may be a Google config issue. There you can choose multiple languages

**Comment by georgjaehnig** [comment]
Closing as it works at least for OP.

If anything, reopen new issue on https://github.com/trovu/trovu-web/issues
