### ISSUE TITLE
Clearer documentation for namespaces

### ISSUE THREAD

**Issue by omarkohl** [trovu/trovu.github.io#6]
I'm struggling a little with namespaces and I think clearer documentation, in particular more examples would be very valuable.

I'll give some examples.

* In this table in the Wiki https://github.com/trovu/trovu.github.io/wiki/Namespaces#namespace-types in the "Example shortcuts" column the "language" example says `en tree` i.e. the namespace `en` is part of the example query. But on the second line the "country" namespace is not part of the example query. It should be `.de.db berlin, hamburg`, correct? The same applies to the other examples in that table. They don't include the namespace.
* How should namespaces be chained? Always with dots or whitespace or both? Do the namespaces have to be always listed in the same order e.g. country before language if you want to include both?
* In the section https://github.com/trovu/trovu.github.io/wiki/Namespaces#forcing-a-namespace it gives the example query `de.en tree` That again confuses me because I thought dot and 2 chars is for countries and `.en` is not a country. Or is this because of the chaining of the namespaces? Are two language namespaces being chained here? Below that it also says "prefixing the query with `de.` forced ..." which again confuses me because it sounds like the namespace has a dot at the **end**. Is that correct?

**Comment by georgjaehnig** [comment]
Hi, thanks for your ticket, it inspired me to [rewrite the docs here](https://github.com/trovu/trovu.github.io/wiki/Namespaces).

> In this table in the Wiki https://github.com/trovu/trovu.github.io/wiki/Namespaces#namespace-types in the "Example shortcuts" column the "language" example says en tree i.e. the namespace en is part of the example query.

This confusion probably arises because `en` can be many things: a keyword, a namespace name and a language setting. So I replaced the example now with `mw`, which in Trovu is only a keyword.

> But on the second line the "country" namespace is not part of the example query. It should be .de.db berlin, hamburg, correct? The same applies to the other examples in that table. They don't include the namespace.

Yes, they all don't include the namespace, because (given the right settings) you can call them without a namespace. I only wanted to give query examples here. I now added from which namespace they come.

> How should namespaces be chained? Always with dots or whitespace or both? Do the namespaces have to be always listed in the same order e.g. country before language if you want to include both?

There is no "chaining" possible, in the sense of forcing multiple namespaces in a query. Only one namespace can prefix a query, and this is possible with `[namespace].`. So we can call

- `mw tree` if we subscribed to the en namespace already
- `en.mw tree` if we haven't subscribed to the en namespace, but want to do so just for this one query

The space after `mw` is then only part of the usual query, it separates keyword from argument(s).

> That again confuses me because I thought dot and 2 chars is for countries and .en is not a country.

This confusion probably arises because `.` can be either 

1. a separator when forcing a namespace (prefixing the query with it)
1. the beginning of a namespace name if it's a country namespace

So in `.de.db berlin, hamburg`, the first dot is 2,, the second dot is 1.

I had already thought about changing one of the dots to something else, to avoid this possible confusion, but had no good idea for an alternative. The char should be possible to type only with one keystroke on most keyboards, without any Shift or similar.

Hope it's clearer now, if not feel free to ask more.

**Comment by omarkohl** [comment]
That is indeed clearer, thanks! A few more questions, though.

This example is not yet clear to me https://github.com/trovu/trovu.github.io/wiki/Namespaces#example

What is `en` in the query `de.en tree`? Another namespace? Aren't you chaining namespaces, then? You write:

> So this query is now processed as if the settings were:
```
language: de
country: us
namespaces:
- o
- en
- .us
- de
```

So there are two language namespace `de` and `en`, right?

What happens when there are collisions between the namespaces? What if a certain keyword does NOT appear in `de` but does appear in `en`?

At the end you write:

> Instead of the French-English dictionary (from fr), the shortcut for the German-English dictionary (from de) is called – because dictionaries are picked via [Includes](https://github.com/trovu/trovu.github.io/wiki/Includes) based on the language setting.

There no longer is `fr` in the example so probably you forgot to update that last paragraph :slightly_smiling_face:

---

> I had already thought about changing one of the dots to something else, to avoid this possible confusion, but had no good idea for an alternative. The char should be possible to type only with one keystroke on most keyboards, without any Shift or similar.

I think re-using the dot is quite confusing, yes. I suggest replacing the dot for use-case 1 (forcing a namespace) with a colon, even though it requires Shift. `.de:db berlin, hamburg`.

**Comment by georgjaehnig** [comment]
> What is `en` in the query `de.en tree`? Another namespace? 

`en` was here a keyword.

So I've [changed](https://github.com/trovu/trovu.github.io/wiki/Namespaces#query) the example now to `de.w berlin`.

> So there are two language namespace de and en, right?

Yes.

> What happens when there are collisions between the namespaces? 

This is regulated by namespace precedence: The lower a namespace is in the list, the higher it's precedence. (Similar to methods of inheriting classes.)

In our example, if the same keyword existed in `en` and `de`, the `de` one would have been picked. Because in our subscribed namespaces (for this query), `de` comes after `en`. 

> What if a certain keyword does NOT appear in de but does appear in en?

Then the one from `en` is picked.

To match a query with a shortcut, the currently subscribed namespaces are searched for the current keyword, from last to first. The first match is then taken.

> There no longer is fr in the example so probably you forgot to update that last paragraph 🙂

Yes, fixed that now. :)

> I think re-using the dot is quite confusing, yes. I suggest replacing the dot for use-case 1 (forcing a namespace) with a colon, even though it requires Shift. `.de:db berlin, hamburg`.

Hm, I'm really reluctant, as this would make it slower to type.

An idea could be to change it to `,`, as this is also accessible without Shift: `.de,db berlin, hamburg`

But somehow this doesn't look good.

Changing this char would also be a breaking change to many existing users. 

If you really think it's a good idea, please create a new ticket in [trovu-web](https://github.com/trovu/trovu-web/issues) and we can discuss it there, incl. possible alternatives.

**Comment by omarkohl** [comment]
Excellent, thanks!

I created https://github.com/trovu/trovu-web/issues/146 for the namespace separator question.
